/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import deepspace.*;
import java.awt.Component;
import java.util.ArrayList;
/**
 *
 * @author victor
 */
public class HangarView extends javax.swing.JPanel {
    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
    }
    
    public void setHangar(HangarToUI h){
     String titulo = "Hangar de " + Integer.toString(h.getMaxElements()) + " espacios";
     setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), titulo));
        //lEspacio.setText("Espacio de " + Integer.toString(h.getMaxElements()));
     pHangar.removeAll();
        for(ShieldToUI s: h.getShieldBoosters()){
            ShieldView sw = new ShieldView();
            sw.setShieldBooster(s);
            pHangar.add(sw);
        }
        
        for(WeaponToUI w: h.getWeapons()){
            WeaponView wv = new WeaponView();
            wv.setWeapon(w);
            pHangar.add(wv);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollHangar = new javax.swing.JScrollPane();
        pHangar = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Hangar"));

        scrollHangar.setViewportView(pHangar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollHangar, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<Integer> getSelected(){
        ArrayList<Integer> selected = new ArrayList();
        int i = 0;
        for (Component c : pHangar.getComponents()) {
            if (((CombatElementView) c).isSelected()) {
                selected.add(i);
            }
            i++;
        }
        return selected;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pHangar;
    private javax.swing.JScrollPane scrollHangar;
    // End of variables declaration//GEN-END:variables
}
