/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import static GUI.MainView.controller;
import deepspace.*;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author victor
 */
public class InfoStation extends javax.swing.JPanel {
    HangarView h;
    /**
     * Creates new form InfoStation
     */
    public InfoStation() {
        initComponents();
        h = new HangarView();
        pHangar.add(h); 
        repaint();
        revalidate();
    }

    public void setStation(SpaceStationToUI st) {
        nombreActual.setText(st.getName());
        fuego.setText(Double.toString(st.getAmmoPower()));
        defensa.setText(Double.toString(st.getShieldPower()));
        medallas.setText(Integer.toString(st.getnMedals()));
        combustible.setText(Double.toString(st.getFuelUnits()));
        pPendingDamage.removeAll();
        if(st.getPendingDamage() != null){
            DamageView d = new DamageView();
            d.setDamage(st.getPendingDamage());
            pPendingDamage.add(d);
        }
        
        pArmas.removeAll();
        pShields.removeAll();
        if(st.getHangar() == null){
            pHangar.setVisible(false);
            bDescartarCompleto.setEnabled(false);
        }else {
            h.setHangar(st.getHangar());
            lHayHangar.setVisible(false);
            bDescartarCompleto.setEnabled(true);
        }
        
        for(WeaponToUI w : st.getWeapons()){
            WeaponView wv = new WeaponView();
            wv.setWeapon(w);
            pArmas.add(wv);
        }
        
        for(ShieldToUI s : st.getShieldBoosters()){
            ShieldView sv = new ShieldView();
            sv.setShieldBooster(s);
            pShields.add(sv);
        }

        GameState gs = controller.getState();
        if(gs == GameState.INIT){
            bEquipar.setEnabled(true);
        }
        else if(gs == GameState.BEFORECOMBAT){
            bEquipar.setEnabled(false);
        }
        else if (gs== GameState.AFTERCOMBAT){
            bEquipar.setEnabled(true);
        }
        
        repaint();
        revalidate();
    }    
            
    public ArrayList<Integer> getSelectedWeapons(){
        ArrayList<Integer> selected = new ArrayList();
        int i = 0;
        for (Component c : pArmas.getComponents()) {
            if (((CombatElementView) c).isSelected()) {
                selected.add(i);
            }
            i++;
        }
        return selected;
    }    
            
    public ArrayList<Integer> getSelectedShields(){
        ArrayList<Integer> selected = new ArrayList();
        int i = 0;
        for (Component c : pShields.getComponents()) {
            if (((CombatElementView) c).isSelected()) {
                selected.add(i);
            }
            i++;
        }
        return selected;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloInfoStation = new javax.swing.JLabel();
        nombretxt = new javax.swing.JLabel();
        nombreActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fuego = new javax.swing.JLabel();
        defensa = new javax.swing.JLabel();
        medallas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combustible = new javax.swing.JLabel();
        scrollWeapons = new javax.swing.JScrollPane();
        pArmas = new javax.swing.JPanel();
        scrollShields = new javax.swing.JScrollPane();
        pShields = new javax.swing.JPanel();
        pHangar = new javax.swing.JPanel();
        bEquipar = new javax.swing.JButton();
        bDescartar = new javax.swing.JButton();
        bDescartarCompleto = new javax.swing.JButton();
        lHayHangar = new javax.swing.JLabel();
        pPendingDamage = new javax.swing.JPanel();

        tituloInfoStation.setText("Información Estación Espacial Actual");

        nombretxt.setText("Nombre: ");

        nombreActual.setText("jLabel1");

        jLabel1.setText("Potencia de fuego: ");

        jLabel2.setText("Potencia de defensa: ");

        jLabel3.setText("Medallas: ");

        fuego.setText("jLabel4");

        defensa.setText("jLabel5");

        medallas.setText("jLabel6");

        jLabel4.setText("Combustible:");

        combustible.setText("jLabel5");

        scrollWeapons.setBorder(javax.swing.BorderFactory.createTitledBorder("Armas montadas"));
        scrollWeapons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollWeaponsMouseClicked(evt);
            }
        });

        pArmas.setBackground(new java.awt.Color(237, 227, 227));
        scrollWeapons.setViewportView(pArmas);

        scrollShields.setBorder(javax.swing.BorderFactory.createTitledBorder("Escudos montados"));
        scrollShields.setViewportView(pShields);

        bEquipar.setText("Equipar");
        bEquipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEquiparActionPerformed(evt);
            }
        });

        bDescartar.setText("Descartar");
        bDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDescartarActionPerformed(evt);
            }
        });

        bDescartarCompleto.setText("Descartar Hangar Completo");
        bDescartarCompleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDescartarCompletoMouseClicked(evt);
            }
        });

        lHayHangar.setText("No tienes hangar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lHayHangar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pPendingDamage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pHangar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(tituloInfoStation, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(nombretxt))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fuego)
                                            .addComponent(nombreActual)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(defensa)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medallas)
                                    .addComponent(combustible))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollShields, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollWeapons))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bEquipar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDescartarCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloInfoStation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombretxt)
                    .addComponent(nombreActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fuego)
                    .addComponent(jLabel3)
                    .addComponent(medallas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(defensa)
                        .addComponent(jLabel4)
                        .addComponent(combustible)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollShields, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lHayHangar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEquipar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDescartar)
                    .addComponent(bDescartarCompleto))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEquiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEquiparActionPerformed
        // TODO add your handling code here:
       MainView.controller.mountCombatElements(h.getSelected());
    }//GEN-LAST:event_bEquiparActionPerformed

    private void bDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDescartarActionPerformed
        // TODO add your handling code here:
           MainView.controller.discardCombatElements(h.getSelected(), getSelectedWeapons(), getSelectedShields());
       
    }//GEN-LAST:event_bDescartarActionPerformed

    private void scrollWeaponsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollWeaponsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_scrollWeaponsMouseClicked

    private void bDescartarCompletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDescartarCompletoMouseClicked
        // TODO add your handling code here:
        MainView.controller.discardHangar();
    }//GEN-LAST:event_bDescartarCompletoMouseClicked


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDescartar;
    private javax.swing.JButton bDescartarCompleto;
    private javax.swing.JButton bEquipar;
    private javax.swing.JLabel combustible;
    private javax.swing.JLabel defensa;
    private javax.swing.JLabel fuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lHayHangar;
    private javax.swing.JLabel medallas;
    private javax.swing.JLabel nombreActual;
    private javax.swing.JLabel nombretxt;
    private javax.swing.JPanel pArmas;
    private javax.swing.JPanel pHangar;
    private javax.swing.JPanel pPendingDamage;
    private javax.swing.JPanel pShields;
    private javax.swing.JScrollPane scrollShields;
    private javax.swing.JScrollPane scrollWeapons;
    private javax.swing.JLabel tituloInfoStation;
    // End of variables declaration//GEN-END:variables
}
