/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import deepspace.*;

/**
 *
 * @author vicas
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form Loot
     */
    public LootView() {
        initComponents();
    }
    
    void setLoot(LootToUI lt) {
        lWeapons.setText(Integer.toString(lt.getnWeapons()));
        lShields.setText(Integer.toString(lt.getnMedals()));
        lHangar.setText(Integer.toString(lt.getnHangars()));
        nSupplies.setText(Integer.toString(lt.getnSupplies()));
        lMedals.setText(Integer.toString(lt.getnMedals()));
        if(lt.isGetEfficient()) {
            lTransform.setText("Estación Eficiente");
        } else if(lt.isSpaceCity()) {
            lTransform.setText("Ciudad espacial");
        } else {
            lTransform.setVisible(false);            
        }
        
        repaint();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lWeapons = new javax.swing.JLabel();
        lShields = new javax.swing.JLabel();
        lHangar = new javax.swing.JLabel();
        nSupplies = new javax.swing.JLabel();
        lMedals = new javax.swing.JLabel();
        lTransform = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tesoro"));

        jLabel1.setText("Armas: ");

        jLabel2.setText("Escudos: ");

        jLabel3.setText("Tamaño Hangar: ");

        jLabel4.setText("Suministros:");

        jLabel5.setText("Medallas: ");

        lWeapons.setText("jLabel6");

        lShields.setText("jLabel6");

        lHangar.setText("jLabel6");

        nSupplies.setText("jLabel6");

        lMedals.setText("jLabel6");

        lTransform.setText("Transforma: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lWeapons)
                    .addComponent(lHangar)
                    .addComponent(lShields))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lMedals))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(nSupplies)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTransform)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lMedals)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTransform))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lWeapons)
                                .addComponent(jLabel4)
                                .addComponent(nSupplies))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lShields))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lHangar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lHangar;
    private javax.swing.JLabel lMedals;
    private javax.swing.JLabel lShields;
    private javax.swing.JLabel lTransform;
    private javax.swing.JLabel lWeapons;
    private javax.swing.JLabel nSupplies;
    // End of variables declaration//GEN-END:variables
}
