/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import View.*;
import Controller.*;
import GUI.*;
import java.util.ArrayList;
import deepspace.*;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class MainView extends javax.swing.JFrame  implements View {
    static Controller controller;
    InfoStation station;
    EnemyView enemy;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        station = new InfoStation();
        pStation.add(station);
        enemy = new EnemyView();
        pEnemy.add(enemy);   
        //Cerrar ventanita
//        setLocationRelativeTo(null);
//        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent e) {
//                controller.finish(0);
//            }
//        });
//        
    }

    public void setController (Controller c) {
        controller = c;
    }
    public void updateView() {
        station.setStation(controller.currentStation());
        GameState gs = controller.getState();
        if(gs == GameState.INIT){
            pEnemy.setVisible(false);
            bSigTurno.setEnabled(false);
            bCombatir.setEnabled(true);
        }
        else if(gs == GameState.BEFORECOMBAT){
            pEnemy.setVisible(false);
            bSigTurno.setEnabled(false);
            bCombatir.setEnabled(true);
        }
        else if (gs== GameState.AFTERCOMBAT){
            pEnemy.setVisible(true);
            enemy.setEnemy(controller.currentEnemy());
            bSigTurno.setEnabled(true);
            bCombatir.setEnabled(false);
        }
        repaint();
    }
    
    public void showView() {
        this.setVisible(true);    
    }
    
    public ArrayList<String> getNames(){
        NamesCapture namesCaptureDialog = new NamesCapture(this,true);
         ArrayList<String> names = namesCaptureDialog.getNames();
         return names;
    }
    
    
    public void resultadoCombate(CombatResult c){
        String cout= "";
         switch (c) {
              case ENEMYWINS :
                cout ="Has PERDIDO el combate. Cumple tu castigo. ";
                break;
              case STATIONESCAPES :
                cout = "Has logrado escapar. Eres una Gallina Espacial.";
                break;
              case STATIONWINS :
                cout = "Has GANADO el combate. Disfruta de tu botín.";
                if (controller.haveAWinner()) {
                  JOptionPane.showMessageDialog(this, "¡Enhorabuena! Has ganado la partida." , "Deepspace message" , JOptionPane.INFORMATION_MESSAGE);
                  controller.finish(0);
                }
                break;
              case STATIONWINSANDCONVERTS : 
                    cout = "¡Has ganado y te has transformado!";
         }
        JOptionPane.showMessageDialog(this, cout , "Deepspace message" , JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void pendingDamageMessage(){
        JOptionPane.showMessageDialog(this, "Aún tiene un daño pendiente" , "Deepspace message" , JOptionPane.INFORMATION_MESSAGE);
    }
    

    @Override
    public boolean confirmExitMessage() {
        return (JOptionPane.showConfirmDialog(this, "¿Estás segur@ que deseas salir?", "Deepspace", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pStation = new javax.swing.JPanel();
        pEnemy = new javax.swing.JPanel();
        bCombatir = new javax.swing.JButton();
        bSigTurno = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pEnemy.setBackground(new java.awt.Color(230, 225, 225));

        bCombatir.setText("¡Combatir!");
        bCombatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombatirActionPerformed(evt);
            }
        });

        bSigTurno.setText("Siguiente Turno");
        bSigTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSigTurnoActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pStation, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bSigTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bCombatir, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCombatir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSigTurno)
                            .addComponent(bSalir))
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        controller.finish(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bCombatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCombatirActionPerformed
        // TODO add your handling code here:
        CombatResult c = controller.combat();  
        controller.resultadoCombate(c);
    }//GEN-LAST:event_bCombatirActionPerformed

    private void bSigTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSigTurnoActionPerformed
        // TODO add your handling code here:
        if(!controller.nextTurn())
            controller.pendingDamageMessage();
            
    }//GEN-LAST:event_bSigTurnoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCombatir;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bSigTurno;
    private javax.swing.JPanel pEnemy;
    private javax.swing.JPanel pStation;
    // End of variables declaration//GEN-END:variables
}
